// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 /*import 'firebase_options.dart';

await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform,
);*/

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzG5GwPxd3Ul_lh-0eCNk8hjSTVXcx4c4',
    appId: '1:191308332361:web:79fa105cf23c6b5e762e98',
    messagingSenderId: '191308332361',
    projectId: 'saivinayakpowersystem',
    authDomain: 'saivinayakpowersystem.firebaseapp.com',
    storageBucket: 'saivinayakpowersystem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPEH3scAMYQPNTJi8hNPPbQ6B6QEzJYGY',
    appId: '1:191308332361:android:87904bc0d3e22f3f762e98',
    messagingSenderId: '191308332361',
    projectId: 'saivinayakpowersystem',
    storageBucket: 'saivinayakpowersystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQCn5IPadFiifWpslNGl5yF61rxar4sM',
    appId: '1:191308332361:ios:8952ecacc414d942762e98',
    messagingSenderId: '191308332361',
    projectId: 'saivinayakpowersystem',
    storageBucket: 'saivinayakpowersystem.appspot.com',
    iosClientId: '191308332361-jkhlfts75393f9pohu8f1dsrlf9foj12.apps.googleusercontent.com',
    iosBundleId: 'org.saivinayak.power.systems.saiVinayakPowerSystems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhQCn5IPadFiifWpslNGl5yF61rxar4sM',
    appId: '1:191308332361:ios:8952ecacc414d942762e98',
    messagingSenderId: '191308332361',
    projectId: 'saivinayakpowersystem',
    storageBucket: 'saivinayakpowersystem.appspot.com',
    iosClientId: '191308332361-jkhlfts75393f9pohu8f1dsrlf9foj12.apps.googleusercontent.com',
    iosBundleId: 'org.saivinayak.power.systems.saiVinayakPowerSystems',
  );
}
